// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/admin"
	"entgo.io/bug/ent/user"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MemberAdminID holds the value of the "member_admin_id" field.
	MemberAdminID int `json:"member_admin_id,omitempty"`
	// LeadAdminID holds the value of the "lead_admin_id" field.
	LeadAdminID int `json:"lead_admin_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"`
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// MemberAdmin holds the value of the member_admin edge.
	MemberAdmin *Admin `json:"member_admin,omitempty"`
	// LeadAdmin holds the value of the lead_admin edge.
	LeadAdmin *Admin `json:"lead_admin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MemberAdminOrErr returns the MemberAdmin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) MemberAdminOrErr() (*Admin, error) {
	if e.loadedTypes[0] {
		if e.MemberAdmin == nil {
			// The edge member_admin was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.MemberAdmin, nil
	}
	return nil, &NotLoadedError{edge: "member_admin"}
}

// LeadAdminOrErr returns the LeadAdmin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) LeadAdminOrErr() (*Admin, error) {
	if e.loadedTypes[1] {
		if e.LeadAdmin == nil {
			// The edge lead_admin was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.LeadAdmin, nil
	}
	return nil, &NotLoadedError{edge: "lead_admin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID, user.FieldAge, user.FieldMemberAdminID, user.FieldLeadAdminID:
			values[i] = new(sql.NullInt64)
		case user.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type User", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				u.Age = int(value.Int64)
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				u.Name = value.String
			}
		case user.FieldMemberAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_admin_id", values[i])
			} else if value.Valid {
				u.MemberAdminID = int(value.Int64)
			}
		case user.FieldLeadAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lead_admin_id", values[i])
			} else if value.Valid {
				u.LeadAdminID = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryMemberAdmin queries the "member_admin" edge of the User entity.
func (u *User) QueryMemberAdmin() *AdminQuery {
	return (&UserClient{config: u.config}).QueryMemberAdmin(u)
}

// QueryLeadAdmin queries the "lead_admin" edge of the User entity.
func (u *User) QueryLeadAdmin() *AdminQuery {
	return (&UserClient{config: u.config}).QueryLeadAdmin(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return (&UserClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", u.Age))
	builder.WriteString(", name=")
	builder.WriteString(u.Name)
	builder.WriteString(", member_admin_id=")
	builder.WriteString(fmt.Sprintf("%v", u.MemberAdminID))
	builder.WriteString(", lead_admin_id=")
	builder.WriteString(fmt.Sprintf("%v", u.LeadAdminID))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User

func (u Users) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
